{{- if .Values.serviceMonitor.enabled  -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "ttjs.fullname" . }}
  namespace: {{ quote (or .Values.serviceMonitor.namespace .Release.Namespace) }}
  labels:
    {{- include "ttjs.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.rules.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  groups:
    - name: ttjs.rules
      rules:
        - alert: TheThingsJoinServerNoJoinsAccepted
          expr: sum(rate(ttjs_activations_total{namespace="{{ .Release.Namespace }}",job="{{ include "ttjs.fullname" . }}",error_type=""}[5m])) == 0
          for: {{ .Values.rules.noJoinsAcceptedFor | default "15m" | quote }}
          labels:
            severity: high
          annotations:
            description: |-
              The Things Join Server {{ .Release.Namespace }}/{{ include "ttjs.fullname" . }} did not accept a join-request.
{{- end }}