{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ttjs.serviceAccountName" . }}
  labels:
    {{- include "ttjs.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ . }}
    {{- end }}
{{- end }}
